# Generated by Django 3.0.5 on 2020-04-01 14:01

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('rating', models.FloatField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=account.models.User.upload_dir_profile_image)),
                ('resume', models.FileField(blank=True, null=True, upload_to=account.models.User.upload_dir_resume)),
            ],
        ),
    ]
